import 'package:cloud_firestore/cloud_firestore.dart';

class Story {
  final String id;
  final String title;
  final List<String> participantIds;
  final List<String> chapterIds; // Shot IDs in order
  final DateTime createdAt;
  final DateTime updatedAt;
  final String createdBy;
  final StoryStatus status;
  final String? autoGeneratedTitle;

  Story({
    required this.id,
    required this.title,
    required this.participantIds,
    required this.chapterIds,
    required this.createdAt,
    required this.updatedAt,
    required this.createdBy,
    this.status = StoryStatus.ongoing,
    this.autoGeneratedTitle,
  });

  // Create from Firestore
  factory Story.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    
    return Story(
      id: doc.id,
      title: data['title'] ?? '',
      participantIds: List<String>.from(data['participantIds'] ?? []),
      chapterIds: List<String>.from(data['chapterIds'] ?? []),
      createdAt: (data['createdAt'] as Timestamp).toDate(),
      updatedAt: (data['updatedAt'] as Timestamp).toDate(),
      createdBy: data['createdBy'] ?? '',
      status: StoryStatus.values.firstWhere(
        (s) => s.toString() == 'StoryStatus.${data['status']}',
        orElse: () => StoryStatus.ongoing,
      ),
      autoGeneratedTitle: data['autoGeneratedTitle'],
    );
  }

  // Convert to Firestore map
  Map<String, dynamic> toFirestore() {
    return {
      'title': title,
      'participantIds': participantIds,
      'chapterIds': chapterIds,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
      'createdBy': createdBy,
      'status': status.toString().split('.').last,
      'autoGeneratedTitle': autoGeneratedTitle,
    };
  }

  Story copyWith({
    String? title,
    List<String>? participantIds,
    List<String>? chapterIds,
   DateTime? updatedAt,
    StoryStatus? status,
  }) {
    return Story(
      id: id,
      title: title ?? this.title,
      participantIds: participantIds ?? this.participantIds,
      chapterIds: chapterIds ?? this.chapterIds,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      createdBy: createdBy,
      status: status ?? this.status,
      autoGeneratedTitle: autoGeneratedTitle,
    );
  }
}

enum StoryStatus {
  ongoing,
  complete,
  archived,
}

// Story connection suggestion (for auto-detection)
class StoryConnection {
  final String fromShotId;
  final String toShotId;
  final double confidenceScore;
  final List<String> reasons; // ["mentioned_user", "keyword_match", "time_proximity"]
  final DateTime detectedAt;
  final ConnectionStatus status;

  StoryConnection({
    required this.fromShotId,
    required this.toShotId,
    required this.confidenceScore,
    required this.reasons,
    required this.detectedAt,
    this.status = ConnectionStatus.pending,
  });

  factory StoryConnection.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    
    return StoryConnection(
      fromShotId: data['fromShotId'],
      toShotId: data['toShotId'],
      confidenceScore: data['confidenceScore']?.toDouble() ?? 0.0,
      reasons: List<String>.from(data['reasons'] ?? []),
      detectedAt: (data['detectedAt'] as Timestamp).toDate(),
      status: ConnectionStatus.values.firstWhere(
        (s) => s.toString() == 'ConnectionStatus.${data['status']}',
        orElse: () => ConnectionStatus.pending,
      ),
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'fromShotId': fromShotId,
      'toShotId': toShotId,
      'confidenceScore': confidenceScore,
      'reasons': reasons,
      'detectedAt': Timestamp.fromDate(detectedAt),
      'status': status.toString().split('.').last,
    };
  }
}

enum ConnectionStatus {
  pending,    // Suggested, awaiting user action
  accepted,   // User confirmed, story created
  rejected,   // User dismissed
  expired,    // Too old, no longer relevant
}

// User profile (cloud version)
class UserProfile {
  final String uid;
  final String email;
  final String? displayName;
  final String? photoUrl;
  final List<String> friendIds;
  final List<String> circleIds; // Family circles they belong to
  final DateTime createdAt;
  final DateTime lastActive;
  
  UserProfile({
    required this.uid,
    required this.email,
    this.displayName,
    this.photoUrl,
    this.friendIds = const [],
    this.circleIds = const [],
    required this.createdAt,
    required this.lastActive,
  });

  factory UserProfile.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    
    return UserProfile(
      uid: doc.id,
      email: data['email'] ?? '',
      displayName: data['displayName'],
      photoUrl: data['photoUrl'],
      friendIds: List<String>.from(data['friendIds'] ?? []),
      circleIds: List<String>.from(data['circleIds'] ?? []),
      createdAt: (data['createdAt'] as Timestamp).toDate(),
      lastActive: (data['lastActive'] as Timestamp).toDate(),
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'email': email,
      'displayName': displayName,
      'photoUrl': photoUrl,
      'friendIds': friendIds,
      'circleIds': circleIds,
      'createdAt': Timestamp.fromDate(createdAt),
      'lastActive': Timestamp.fromDate(lastActive),
    };
  }
}
