// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPhCoyC-aslERNqxEvO9GLshsCsWOO2w',
    appId: '1:503909518866:web:88caf321dbeec379ad92cb',
    messagingSenderId: '503909518866',
    projectId: 'estv01-8a473bce',
    authDomain: 'estv01-8a473bce.firebaseapp.com',
    storageBucket: 'estv01-8a473bce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzTpU-oUhfiCWadYHF25koMZOZ6fVuX0',
    appId: '1:503909518866:android:f032b8ca31f46b53ad92cb',
    messagingSenderId: '503909518866',
    projectId: 'estv01-8a473bce',
    storageBucket: 'estv01-8a473bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUruJRt5OqrJuKqCwJWjNQcuQSK_7Z1L8',
    appId: '1:503909518866:ios:076fa09d392e7196ad92cb',
    messagingSenderId: '503909518866',
    projectId: 'estv01-8a473bce',
    storageBucket: 'estv01-8a473bce.firebasestorage.app',
    androidClientId: '503909518866-3ii0ob8grqrcgejnp1t14ufcbvhgp9i4.apps.googleusercontent.com',
    iosClientId: '503909518866-5s0qicvmotn8dq14bcukj3766ts9ifpl.apps.googleusercontent.com',
    iosBundleId: 'com.enjoysuper.est',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUruJRt5OqrJuKqCwJWjNQcuQSK_7Z1L8',
    appId: '1:503909518866:ios:076fa09d392e7196ad92cb',
    messagingSenderId: '503909518866',
    projectId: 'estv01-8a473bce',
    storageBucket: 'estv01-8a473bce.firebasestorage.app',
    androidClientId: '503909518866-3ii0ob8grqrcgejnp1t14ufcbvhgp9i4.apps.googleusercontent.com',
    iosClientId: '503909518866-5s0qicvmotn8dq14bcukj3766ts9ifpl.apps.googleusercontent.com',
    iosBundleId: 'com.enjoysuper.est',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcPhCoyC-aslERNqxEvO9GLshsCsWOO2w',
    appId: '1:503909518866:web:5a719e19c5331b6ead92cb',
    messagingSenderId: '503909518866',
    projectId: 'estv01-8a473bce',
    authDomain: 'estv01-8a473bce.firebaseapp.com',
    storageBucket: 'estv01-8a473bce.firebasestorage.app',
  );
}
